import json
import re
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = Path("D:/edu4bharat/chapter_manifest.json")
OUT = ROOT / "services" / "companion" / "pyqSourceCatalog.ts"


def infer_exam(entry):
    board = str(entry.get("board") or "unknown").lower()
    file_path = str(entry.get("file_path") or "").lower()
    file_name = str(entry.get("file_name") or "").lower()
    joined = f"{board} {file_path} {file_name}"
    if "tnpsc" in joined or "tn-specific" in joined:
        return "TNPSC"
    if "upsc" in joined or "ias" in joined:
        return "UPSC"
    if "ssc" in joined or "cgl" in joined or "chsl" in joined or "mts" in joined:
        return "SSC"
    if "neet" in joined:
        return "NEET"
    if "jee" in joined:
        return "JEE"
    if "banking" in joined or "ibps" in joined or "sbi" in joined:
        return "Banking"
    if "railway" in joined or "rrb" in joined:
        return "Railway"
    return board.upper()


def clean_label(value):
    value = re.sub(r"\.pdf$", "", str(value or ""), flags=re.I)
    value = re.sub(r"[-_]+", " ", value)
    value = re.sub(r"\s+", " ", value).strip()
    return value.title() if value else "Previous Year Paper"


def main():
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    source_root = manifest.get("source_root") or "D:/edu4bharat/raw"
    entries = [
        entry for entry in manifest.get("entries", [])
        if entry.get("source_type") == "pyq" and str(entry.get("file_path") or "").lower().endswith(".pdf")
    ]

    sources = []
    coverage = defaultdict(lambda: {
        "exam": "",
        "paperCount": 0,
        "years": set(),
        "boards": Counter(),
        "latestYear": None,
        "earliestYear": None,
    })

    for entry in entries:
        exam = infer_exam(entry)
        year = entry.get("year")
        file_path = str(entry.get("file_path") or "")
        source = {
            "id": entry.get("id"),
            "exam": exam,
            "board": entry.get("board"),
            "year": year,
            "language": entry.get("language"),
            "title": clean_label(entry.get("file_name")),
            "fileName": entry.get("file_name"),
            "filePath": file_path,
            "sourcePath": str(Path(source_root) / file_path.replace("/", "\\")),
        }
        sources.append(source)

        bucket = coverage[exam]
        bucket["exam"] = exam
        bucket["paperCount"] += 1
        if year:
            bucket["years"].add(int(year))
            bucket["latestYear"] = max(bucket["latestYear"] or int(year), int(year))
            bucket["earliestYear"] = min(bucket["earliestYear"] or int(year), int(year))
        bucket["boards"][str(entry.get("board") or "unknown")] += 1

    coverage_list = []
    for exam, bucket in sorted(coverage.items()):
        coverage_list.append({
            "exam": exam,
            "paperCount": bucket["paperCount"],
            "years": sorted(bucket["years"]),
            "earliestYear": bucket["earliestYear"],
            "latestYear": bucket["latestYear"],
            "boards": dict(bucket["boards"]),
        })

    payload = {
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "sourceRoot": source_root,
        "sourceCount": len(sources),
        "coverage": coverage_list,
        "sources": sorted(sources, key=lambda item: (item["exam"], item.get("year") or 0, item["title"])),
    }

    OUT.write_text(
        "/* Auto-generated by scripts/build_pyq_source_catalog.py. Do not edit manually. */\n"
        "export const PYQ_SOURCE_CATALOG = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + " as const;\n\n"
        "export type PyqSourceCatalog = typeof PYQ_SOURCE_CATALOG;\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} with {len(sources)} PYQ PDF sources")


if __name__ == "__main__":
    main()
