require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const BASE  = process.env.EXPO_PUBLIC_UPSTASH_REDIS_REST_URL;
const TOKEN = process.env.EXPO_PUBLIC_UPSTASH_REDIS_REST_TOKEN;
const KEY   = 'quiz:subject:physics';
const HDR   = { Authorization:`Bearer ${TOKEN}`, 'Content-Type':'application/json' };
async function rpush(items) {
  const values = items.map(q => JSON.stringify(q));
  const r = await fetch(`${BASE}/pipeline`, {
    method: 'POST', headers: HDR,
    body: JSON.stringify([['RPUSH', KEY, ...values]]),
  });
  return r.json();
}
async function del() {
  return fetch(`${BASE}/del/${encodeURIComponent(KEY)}`, { method: 'POST', headers: HDR }).then(r => r.json());
}

const questions = [
  // ── EASY ──
  { question_text:"The SI unit of force is:", options:["Pascal","Joule","Newton","Watt"], correct_answer:2, explanation:"The SI unit of force is the Newton (N), named after Isaac Newton. 1 Newton = 1 kg·m/s² — the force needed to accelerate a 1 kg mass at 1 m/s².", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The SI unit of work and energy is:", options:["Newton","Pascal","Watt","Joule"], correct_answer:3, explanation:"The SI unit of work and energy is the Joule (J). 1 Joule = 1 Newton × 1 metre (force times displacement). Named after James Prescott Joule.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The SI unit of power is:", options:["Joule","Watt","Newton","Pascal"], correct_answer:1, explanation:"The SI unit of power is the Watt (W). 1 Watt = 1 Joule/second. Power is the rate of doing work. Named after James Watt.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which law states: 'For every action, there is an equal and opposite reaction'?", options:["Newton's First Law","Newton's Second Law","Newton's Third Law","Hooke's Law"], correct_answer:2, explanation:"Newton's Third Law: Forces always occur in pairs — when object A exerts a force on object B, object B exerts an equal and opposite force on A. Examples: rocket propulsion, swimming, gun recoil.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which type of lens is used to correct short-sightedness (myopia)?", options:["Convex (converging) lens","Concave (diverging) lens","Plano-convex lens","Bifocal lens"], correct_answer:1, explanation:"Myopia (near-sightedness) — image forms in front of retina. Corrected with concave (diverging) lens which diverges light rays. Hypermetropia (far-sightedness) is corrected with convex lens.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The acceleration due to gravity on Earth's surface is approximately:", options:["9.8 m/s²","98 m/s²","0.98 m/s²","9.8 km/s²"], correct_answer:0, explanation:"g = 9.8 m/s² (approximately 10 m/s² for calculations). It varies slightly with latitude (higher at poles, lower at equator) and altitude. On Moon, g = 1.62 m/s² (about 1/6 of Earth's).", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The frequency of AC (Alternating Current) in India is:", options:["50 Hz","60 Hz","100 Hz","25 Hz"], correct_answer:0, explanation:"India uses 50 Hz (cycles per second) AC power supply at 220-240 V. USA uses 60 Hz at 110-120 V. The direction of current alternates 50 times per second in India.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The instrument used to measure atmospheric pressure is:", options:["Thermometer","Hygrometer","Barometer","Anemometer"], correct_answer:2, explanation:"A barometer measures atmospheric pressure. Evangelista Torricelli invented the mercury barometer in 1643. Standard atmospheric pressure = 760 mm Hg = 101,325 Pa.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"What happens to resistance when temperature of a conductor increases?", options:["Resistance decreases","Resistance remains constant","Resistance increases","Resistance becomes zero"], correct_answer:2, explanation:"For conductors (metals), resistance increases with temperature — atoms vibrate more, impeding electron flow. For semiconductors, resistance decreases with temperature. Superconductors have zero resistance below critical temperature.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"A substance that allows electric current to flow through it easily is called:", options:["Insulator","Semiconductor","Conductor","Dielectric"], correct_answer:2, explanation:"Conductors (metals like copper, silver, gold) have free electrons that carry electric current. Insulators (rubber, glass, plastic) block current. Semiconductors (silicon, germanium) partially conduct.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The principle of a hydraulic press is based on:", options:["Boyle's Law","Pascal's Law — pressure applied to a fluid is transmitted equally in all directions","Archimedes' Principle","Newton's Second Law"], correct_answer:1, explanation:"Pascal's Law: pressure applied to an enclosed incompressible fluid is transmitted equally in all directions. Hydraulic press uses this to multiply force: F₂ = F₁ × (A₂/A₁). Used in car brakes, jacks, presses.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The bending of light as it passes from one medium to another is called:", options:["Reflection","Diffraction","Refraction","Dispersion"], correct_answer:2, explanation:"Refraction is the bending of light as it passes from one transparent medium to another of different optical density. Governed by Snell's Law: n₁sinθ₁ = n₂sinθ₂. Causes apparent depth, mirages, and lens action.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },

  // ── MEDIUM ──
  { question_text:"The critical angle for total internal reflection depends on:", options:["The wavelength of light only","The refractive indices of the two media — sin(critical angle) = n₂/n₁","The speed of light in vacuum","Only the temperature"], correct_answer:1, explanation:"Total Internal Reflection occurs when light travels from denser to rarer medium and angle of incidence > critical angle (θc). sin θc = n₂/n₁ (n₁ > n₂). Applications: optical fibre, diamond sparkle, mirages.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The escape velocity from Earth's surface is approximately:", options:["7.9 km/s","11.2 km/s","3 km/s","16 km/s"], correct_answer:1, explanation:"Escape velocity = √(2gR) = √(2 × 9.8 × 6.4×10⁶) ≈ 11.2 km/s. This is the minimum speed needed to escape Earth's gravitational field without further propulsion. Orbital velocity = 7.9 km/s.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Kepler's Second Law (Law of Equal Areas) states that:", options:["Planets move in circular orbits","A planet sweeps equal areas in equal times — moves faster when closer to Sun (perihelion)","Orbital period² ∝ semi-major axis³","Planets have equal orbital velocities"], correct_answer:1, explanation:"Kepler's Second Law: A line joining a planet and the Sun sweeps out equal areas in equal time intervals. This means a planet moves fastest at perihelion (closest to Sun) and slowest at aphelion (farthest), conserving angular momentum.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"A transformer works on the principle of:", options:["Self-induction","Mutual electromagnetic induction — changing magnetic flux in primary coil induces EMF in secondary","Photoelectric effect","Electrostatic induction"], correct_answer:1, explanation:"Transformer works on mutual induction: alternating current in the primary coil creates changing magnetic flux, inducing EMF in secondary coil. V₂/V₁ = N₂/N₁. Step-up transformers increase voltage (N₂>N₁); step-down reduce it.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Doppler Effect refers to:", options:["Change in wavelength of light due to gravity","Apparent change in frequency of a wave when source or observer is moving relative to each other","Diffraction of waves around obstacles","Interference of two waves"], correct_answer:1, explanation:"Doppler Effect: frequency appears higher when source approaches (blue shift) and lower when it recedes (red shift). Applications: RADAR speed guns, astronomical redshift (universe expansion), medical ultrasound (blood flow).", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"In a p-n junction diode, current flows easily (forward bias) when:", options:["Positive terminal connected to n-type, negative to p-type","Positive terminal connected to p-type (anode), negative to n-type (cathode)","No external voltage applied","Only AC voltage applied"], correct_answer:1, explanation:"Forward bias: positive terminal of battery connected to p-type, negative to n-type. This reduces the depletion region and allows current (majority carriers) to flow. Reverse bias blocks current flow (except tiny leakage current).", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Bernoulli principle states that in a flowing fluid:", options:["Pressure increases where speed increases","Where speed is high, pressure is low — and vice versa (conservation of energy in fluids)","Density increases with speed","Temperature decreases with pressure"], correct_answer:1, explanation:"Bernoulli's Principle: For an ideal, incompressible, non-viscous fluid in steady flow: P + ½ρv² + ρgh = constant. Where speed is high, pressure is low. Applications: aircraft wings (lift), Venturi meter, carburettor.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The unit of radioactivity is:", options:["Roentgen","Gray","Sievert","Becquerel (Bq)"], correct_answer:3, explanation:"Becquerel (Bq) is the SI unit of radioactivity — 1 Bq = 1 disintegration per second. Curie (Ci) is older unit (1 Ci = 3.7×10¹⁰ Bq). Gray (Gy) measures absorbed radiation dose. Sievert (Sv) measures biological dose.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The phenomenon of 'resonance' occurs when:", options:["Two waves cancel each other","A body is forced to vibrate at its natural frequency, resulting in large amplitude oscillations","Sound exceeds the speed of light","Temperature causes expansion"], correct_answer:1, explanation:"Resonance occurs when the driving frequency equals the natural frequency of a system, causing maximum energy transfer and large amplitude. Examples: Tacoma Bridge collapse, microwave heating water molecules, MRI using nuclear magnetic resonance.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"In Young's double-slit experiment, the fringe width (β) is:", options:["β = λD/a (directly proportional to wavelength and screen distance, inversely to slit separation)","β = aD/λ","β = λa/D","β = Da/λ"], correct_answer:0, explanation:"Fringe width β = λD/d, where λ=wavelength, D=distance to screen, d=slit separation. This experiment proved the wave nature of light. Bright fringes form where path difference is nλ; dark fringes where path difference is (2n-1)λ/2.", difficulty:"medium", exam_types:["tnpsc","upsc"] },
  { question_text:"Nuclear magnetic resonance (NMR) — the basis of MRI — works because:", options:["Nuclei emit light when heated","Certain atomic nuclei (with odd number of protons/neutrons) have spin and align with an external magnetic field, absorbing and emitting radio waves","X-rays penetrate soft tissue","Electric fields deflect nuclei"], correct_answer:1, explanation:"NMR/MRI: nuclei like ¹H (protons) have quantum mechanical spin. In a strong magnetic field, spins align. RF pulses disturb alignment; as spins relax back, they emit radio waves. Different tissues have different relaxation times — used for soft tissue imaging.", difficulty:"medium", exam_types:["tnpsc","upsc"] },

  // ── HARD ──
  { question_text:"The Compton Effect demonstrated:", options:["Wave nature of electrons","Particle nature of light (photons) — X-ray photons colliding with electrons show elastic collision behaviour with wavelength shift","Wave-particle duality of matter","Gravitational deflection of light"], correct_answer:1, explanation:"Compton Effect (1923): Arthur Compton showed that X-ray photons scatter off electrons and the scattered photons have longer wavelength (Δλ = (h/mc)(1-cosθ)). This proved photons have momentum (p=h/λ) and behave as particles. Confirmed quantum nature of radiation.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The de Broglie wavelength (λ = h/mv) implies:", options:["Only light has wave-particle duality","All matter (particles with mass and velocity) has an associated wave — wave-particle duality is universal","Only electrons behave as waves","Wavelength increases with speed"], correct_answer:1, explanation:"de Broglie (1924) proposed that matter (electrons, protons, even macroscopic objects) has wave properties: λ = h/p = h/mv. Confirmed by Davisson-Germer experiment (1927) — electrons diffracted by nickel crystal, proving matter waves. Basis of electron microscopy.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The Chandrasekhar Limit (~1.4 solar masses) is:", options:["The maximum size of a black hole","The maximum mass of a white dwarf — above this, electron degeneracy pressure cannot prevent collapse","The minimum mass for nuclear fusion","The mass at which a star becomes a supernova"], correct_answer:1, explanation:"Subrahmanyan Chandrasekhar (1930) calculated that a white dwarf cannot exceed 1.4 solar masses (Chandrasekhar Limit). Above this, electron degeneracy pressure fails and the star collapses into a neutron star or black hole. He won the Nobel Prize in 1983.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"Meissner Effect in superconductors refers to:", options:["Infinite electrical resistance above critical temperature","Expulsion of magnetic fields from the interior of a superconductor below critical temperature (perfect diamagnetism)","Light emission when current flows","Josephson tunnelling of Cooper pairs"], correct_answer:1, explanation:"Meissner Effect (1933): Below the critical temperature Tc, a superconductor expels all magnetic flux from its interior (B=0 inside), regardless of whether the field was applied before or after cooling. This is different from perfect conductivity — it's perfect diamagnetism. Enables magnetic levitation.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"In Special Relativity, time dilation means:", options:["Clocks run faster when moving","Moving clocks run slower — a moving clock records less elapsed time than a stationary one (t = t₀/√(1-v²/c²))","Time is absolute","Gravity makes time run slower only"], correct_answer:1, explanation:"Time Dilation (Einstein's Special Relativity): A clock moving relative to an observer runs slower than a stationary clock. The faster the motion, the greater the dilation. At v=0.87c, time runs at half the rate. Confirmed by atomic clocks on aircraft. GPS satellites need relativistic corrections.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
];

async function main() {
  await del();
  console.log('Cleared.');
  const BATCH = 50;
  let total = 0;
  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH);
    await rpush(batch);
    total += batch.length;
    console.log(`Batch ${Math.floor(i/BATCH)+1}: pushed ${batch.length} → total ${total}`);
  }
  console.log(`Done! ${total} physics questions in ${KEY}`);
}
main().catch(console.error);
