require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const BASE  = process.env.EXPO_PUBLIC_UPSTASH_REDIS_REST_URL;
const TOKEN = process.env.EXPO_PUBLIC_UPSTASH_REDIS_REST_TOKEN;
const KEY   = 'quiz:subject:history';
const HDR   = { Authorization:`Bearer ${TOKEN}`, 'Content-Type':'application/json' };

async function rpush(items) {
  const values = items.map(q => JSON.stringify(q));
  const r = await fetch(`${BASE}/pipeline`, {
    method: 'POST', headers: HDR,
    body: JSON.stringify([['RPUSH', KEY, ...values]]),
  });
  return r.json();
}
async function del() {
  return fetch(`${BASE}/del/${encodeURIComponent(KEY)}`, { method: 'POST', headers: HDR }).then(r => r.json());
}

const questions = [
  // ── EASY (Class 6-8 Samacheer / NCERT) ─────────────────────────────────
  { question_text:"The Indus Valley Civilisation was discovered in:", options:["1901","1921","1947","1950"], correct_answer:1, explanation:"The Indus Valley Civilisation was discovered in 1921 when archaeologist Daya Ram Sahni excavated Harappa. The discovery revealed one of the world's oldest urban civilisations.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which river is associated with the Harappan site of Mohenjo-daro?", options:["Ganga","Yamuna","Indus","Brahmaputra"], correct_answer:2, explanation:"Mohenjo-daro is located near the Indus River in present-day Sindh, Pakistan. It was one of the two major cities of the Indus Valley Civilisation, along with Harappa.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The 'Great Bath' was found at which Indus Valley site?", options:["Harappa","Lothal","Mohenjo-daro","Kalibangan"], correct_answer:2, explanation:"The Great Bath was found at Mohenjo-daro. It is considered one of the world's first public water tanks and may have been used for ritual bathing.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The Vedas are written in which language?", options:["Pali","Prakrit","Sanskrit","Tamil"], correct_answer:2, explanation:"The Vedas (Rigveda, Samaveda, Yajurveda, Atharvaveda) are the oldest Hindu scriptures, written in Sanskrit. The Rigveda is the oldest, composed around 1500 BCE.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"How many Vedas are there?", options:["2","3","4","5"], correct_answer:2, explanation:"There are 4 Vedas: Rigveda (hymns to gods), Samaveda (melodies), Yajurveda (rituals), and Atharvaveda (spells and charms). The Rigveda is the oldest.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Ashoka was a ruler of which empire?", options:["Gupta","Mauryan","Kushana","Mughal"], correct_answer:1, explanation:"Ashoka the Great (268–232 BCE) was the third emperor of the Mauryan Empire. He converted to Buddhism after the Kalinga War and spread Buddhist teachings across Asia.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The Kalinga War was fought by Ashoka in approximately:", options:["321 BCE","261 BCE","185 BCE","320 CE"], correct_answer:1, explanation:"The Kalinga War (261 BCE) was fought between Ashoka and the state of Kalinga (modern Odisha). The enormous bloodshed (100,000 killed) led Ashoka to adopt Buddhism and non-violence.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Chandragupta Maurya founded the Mauryan Empire with the help of:", options:["Kalidasa","Chanakya (Kautilya)","Ashoka","Bindusara"], correct_answer:1, explanation:"Chandragupta Maurya (322–297 BCE) founded the Mauryan Empire with the guidance of Chanakya (also known as Kautilya), the author of Arthashastra, a treatise on statecraft.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The Gupta Empire is often called the 'Golden Age' of India because:", options:["It had the largest army","It saw great achievements in art, science, literature, and mathematics","It conquered the most territory","It was the richest empire"], correct_answer:1, explanation:"The Gupta period (4th–6th century CE) is called the Golden Age due to remarkable achievements: Aryabhata discovered zero and pi, Kalidasa wrote Shakuntala, iron pillar was made, decimal system used.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Buddhism was founded by:", options:["Mahavira","Ashoka","Gautama Buddha","Chandragupta"], correct_answer:2, explanation:"Buddhism was founded by Siddhartha Gautama (the Buddha) in the 5th century BCE. He attained enlightenment under the Bodhi tree at Bodh Gaya, Bihar.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Jainism was founded by:", options:["Mahavira","Gautama Buddha","Ashoka","Akbar"], correct_answer:0, explanation:"Jainism's last and 24th Tirthankara is Vardhamana Mahavira (6th century BCE). He preached non-violence (ahimsa), truth, and non-possession. Jains believe in no creator god.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The First Battle of Panipat (1526) was fought between:", options:["Humayun and Sher Shah","Babur and Ibrahim Lodi","Akbar and Hemu","Aurangzeb and Dara Shikoh"], correct_answer:1, explanation:"Babur defeated Ibrahim Lodi at the First Battle of Panipat (1526), establishing the Mughal Empire in India. Babur used artillery and flanking tactics to defeat Lodi's larger army.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Akbar's policy of 'Sulh-i-kul' means:", options:["Rule by force","Universal peace/harmony — tolerance of all religions","Tax exemption for Hindus","Military expansion"], correct_answer:1, explanation:"Sulh-i-kul (Universal Peace) was Akbar's policy of religious tolerance. He abolished jizya (tax on non-Muslims), welcomed scholars of all religions, and started Din-i-Ilahi.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The Battle of Plassey (1757) was fought between:", options:["British and Marathas","British and Siraj-ud-daulah (Bengal Nawab)","British and Hyder Ali","British and Tipu Sultan"], correct_answer:1, explanation:"The Battle of Plassey (1757) was fought between Robert Clive of the British East India Company and Nawab Siraj-ud-daulah of Bengal. British victory established colonial dominance.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The Sepoy Mutiny (First War of Independence) took place in:", options:["1845","1857","1885","1905"], correct_answer:1, explanation:"The 1857 Revolt (also called Sepoy Mutiny or First War of Independence) began on 10 May 1857 at Meerut when Indian soldiers (sepoys) revolted against the British East India Company.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Who founded the Indian National Congress in 1885?", options:["Mahatma Gandhi","A.O. Hume","Bal Gangadhar Tilak","Gopal Krishna Gokhale"], correct_answer:1, explanation:"Allan Octavian Hume, a retired British civil servant, founded the Indian National Congress in 1885 in Bombay. Womesh Chandra Bonnerjee was its first president.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Mahatma Gandhi launched the Non-Cooperation Movement in:", options:["1915","1919","1920","1930"], correct_answer:2, explanation:"The Non-Cooperation Movement was launched by Gandhi in 1920-1922 after the Jallianwala Bagh massacre. Indians were asked to boycott British goods, courts, and educational institutions.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The Dandi March (Salt Satyagraha) was launched in:", options:["1920","1929","1930","1942"], correct_answer:2, explanation:"Gandhi launched the Dandi March on 12 March 1930, walking 241 miles to Dandi, Gujarat to make salt and defy the British salt tax. It became a major act of civil disobedience.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"India gained independence on:", options:["15 August 1945","15 August 1947","26 January 1947","26 January 1950"], correct_answer:1, explanation:"India gained independence on 15 August 1947, when British rule ended. Pakistan was also created on 14 August 1947 (partition). Jawaharlal Nehru became India's first Prime Minister.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Who is called the 'Father of the Nation' in India?", options:["Jawaharlal Nehru","B.R. Ambedkar","Mahatma Gandhi","Sardar Patel"], correct_answer:2, explanation:"Mahatma Gandhi (Mohandas Karamchand Gandhi, 1869–1948) is called the Father of the Nation for leading India's independence movement through non-violent civil disobedience.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The Chola dynasty's greatest ruler, known for naval expeditions, was:", options:["Karikalan","Rajaraja Chola I","Rajendra Chola I","Kulottunga I"], correct_answer:2, explanation:"Rajendra Chola I (1014–1044 CE) launched a naval expedition to Southeast Asia, defeating rulers in Sri Lanka, Maldives, Malaya, and Sumatra. He earned the title 'Gangai Konda Cholan'.", difficulty:"easy", exam_types:["tnpsc","ssc"] },
  { question_text:"Thanjavur Brihadeeswara Temple was built by:", options:["Rajendra Chola I","Rajaraja Chola I","Kulottunga I","Karikalan"], correct_answer:1, explanation:"The Brihadeeswara Temple (Peruvudaiyar Kovil) at Thanjavur was built by Rajaraja Chola I around 1010 CE. It is a UNESCO World Heritage Site and exemplifies Dravidian temple architecture.", difficulty:"easy", exam_types:["tnpsc","ssc"] },

  // ── MEDIUM (Class 9-10 Samacheer / NCERT) ──────────────────────────────
  { question_text:"The Harappan city of Lothal (in Gujarat) was famous for:", options:["The Great Bath","A dockyard for maritime trade","Iron smelting","Buddhist monasteries"], correct_answer:1, explanation:"Lothal had a sophisticated dockyard (dock) for maritime trade — the world's earliest known dock. Ships from Lothal traded with Mesopotamia and Persian Gulf. It shows the Harappans were expert seafarers.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Which Harappan city had a distinct 'lower town' and 'upper citadel' structure?", options:["Lothal","Dholavira","Harappa","Kalibangan"], correct_answer:2, explanation:"Both Harappa and Mohenjo-daro had the pattern of a fortified citadel (upper town) and a lower residential town. Dholavira is unique for its three-part division: citadel, middle town, and lower town.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Vedic age is broadly divided into Early Vedic (Rigvedic) and Later Vedic. The Later Vedic age is associated with:", options:["Nomadic pastoral life only","Growth of agriculture, caste system, and large kingdoms (Mahajanapadas)","Only religious poetry","Seafaring trade"], correct_answer:1, explanation:"The Later Vedic period saw settled agriculture, expansion eastward to Ganga plain, formation of 16 Mahajanapadas (great kingdoms), hardening of the varna (caste) system, and composition of Upanishads.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Megasthenes, who wrote 'Indica', was the ambassador of which ruler to Chandragupta Maurya's court?", options:["Alexander the Great","Seleucus Nikator","Ptolemy","Antiochus"], correct_answer:1, explanation:"Megasthenes was a Greek ambassador sent by Seleucus Nikator (a successor of Alexander) to the court of Chandragupta Maurya. His work 'Indica' provides valuable information about Mauryan India.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Ashoka's Dhamma included:", options:["Conversion to Buddhism by force","Respect for all religions, non-violence, charity, and obedience to parents and elders","Only Buddhist practices","Military campaigns to spread Buddhism"], correct_answer:1, explanation:"Ashoka's Dhamma (not identical to Buddhism) was a moral code: respect for all religions (tolerance), non-violence (ahimsa), truthfulness, charity, respect for elders/parents/teachers, and kindness to animals.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Sangam Age in Tamil history refers to:", options:["6th–3rd century BCE","3rd century BCE–3rd century CE","10th–14th century CE","5th–7th century CE"], correct_answer:1, explanation:"The Sangam Age (approximately 3rd BCE–3rd CE) is a classical period of Tamil history named after the Tamil literary academies (Sangams). The three ruling families were Chera, Chola, and Pandya.", difficulty:"medium", exam_types:["tnpsc","ssc"] },
  { question_text:"The 'Subsidiary Alliance' system introduced by Lord Wellesley in India meant:", options:["British protecting Indian princely states in exchange for military and financial control","Joint military forces between British and Indians","Free trade agreements","Land revenue sharing"], correct_answer:0, explanation:"Under the Subsidiary Alliance, Indian rulers accepted British troops for protection, gave up the right to maintain their own armies, and paid for British troops. Non-compliance led to seizure of territory. Hyderabad was the first to accept (1798).", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The immediate cause of the 1857 Revolt was:", options:["Doctrine of Lapse","Cartridges greased with animal fat for the new Enfield rifle","Imposition of taxes","Partition of Bengal"], correct_answer:1, explanation:"The immediate trigger was the introduction of the Enfield rifle cartridges rumoured to be greased with cow and pig fat, offending both Hindu and Muslim soldiers who had to bite off the cartridge tip.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The 'Doctrine of Lapse' was introduced by:", options:["Lord Cornwallis","Lord Dalhousie","Lord Wellesley","Lord Canning"], correct_answer:1, explanation:"Lord Dalhousie introduced the Doctrine of Lapse (1848–1856): if a ruler died without a natural heir, the state would be annexed to British India (adopted heirs not recognised). Satara, Jhansi, Nagpur were annexed.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Partition of Bengal (1905) was ordered by:", options:["Lord Curzon","Lord Dalhousie","Lord Mountbatten","Lord Ripon"], correct_answer:0, explanation:"Lord Curzon ordered the Partition of Bengal on 16 October 1905, dividing it into East Bengal (Muslim majority) and West Bengal. This sparked the Swadeshi Movement and 'Boycott' agitation.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Jallianwala Bagh massacre took place in:", options:["1905","1915","1919","1921"], correct_answer:2, explanation:"On 13 April 1919 (Baisakhi day), General Reginald Dyer ordered troops to fire on a peaceful crowd at Jallianwala Bagh, Amritsar, killing hundreds. This shocked India and changed the independence movement.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Khilafat Movement (1919–1922) was led by:", options:["Gandhi","Muhammad Ali and Shaukat Ali (Ali brothers)","Jinnah","Maulana Azad"], correct_answer:1, explanation:"The Khilafat Movement was led by Muhammad Ali and Shaukat Ali (Ali brothers) to protest the abolition of the Ottoman Caliphate. Gandhi supported it to unite Hindus and Muslims against the British.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Quit India Movement was launched in:", options:["1939","1940","1942","1945"], correct_answer:2, explanation:"Gandhi launched the Quit India Movement on 9 August 1942 at the Bombay session of Congress, with the slogan 'Do or Die'. It demanded immediate British withdrawal from India.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Indian Constitution was adopted on 26 November 1949 and came into force on:", options:["15 August 1947","26 November 1949","26 January 1950","15 August 1950"], correct_answer:2, explanation:"The Constitution of India was adopted on 26 November 1949 (Constitution Day/Samvidhan Divas) but came into effect on 26 January 1950 (Republic Day), replacing the Government of India Act, 1935.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Vijayanagara Empire's capital city was:", options:["Madurai","Hampi","Golconda","Bijapur"], correct_answer:1, explanation:"The Vijayanagara Empire (1336–1646 CE) had its capital at Hampi (Vijayanagara) on the banks of the Tungabhadra river in Karnataka. It was a major centre of Hindu culture and the Kannada language.", difficulty:"medium", exam_types:["tnpsc","ssc"] },
  { question_text:"Krishnadeva Raya, the greatest ruler of Vijayanagara, patronised:", options:["Urdu literature","Telugu literature and culture","Marathi literature","Tamil literature only"], correct_answer:1, explanation:"Krishnadeva Raya (1509–1529) was a great patron of Telugu literature — he himself wrote 'Amuktamalyada' in Telugu. He was also known as 'Abhinava Bhoja' (new Bhoja).", difficulty:"medium", exam_types:["tnpsc","ssc"] },
  { question_text:"The Battle of Talikota (1565) resulted in:", options:["Vijayanagara defeating the Deccan Sultanates","Destruction of the Vijayanagara Empire by the combined Deccan Sultanates","Mughal victory over Vijayanagara","British defeating Vijayanagara"], correct_answer:1, explanation:"At Talikota, the combined forces of Bijapur, Ahmadnagar, Bidar, and Golconda defeated Vijayanagara and razed the capital Hampi. This ended the Vijayanagara Empire's dominance.", difficulty:"medium", exam_types:["tnpsc","ssc"] },
  { question_text:"The Simon Commission (1927) was boycotted because:", options:["It proposed partition of India","It had no Indian members — all-British commission on Indian constitutional reform","It imposed heavy taxes","It banned the Congress"], correct_answer:1, explanation:"The Simon Commission (led by Sir John Simon) had no Indian members, which was seen as an insult. Indians boycotted it with 'Simon Go Back' protests. It led to the Nehru Report (1928) as an Indian alternative.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Round Table Conferences (1930–32) were held in:", options:["New Delhi","Calcutta","London","Lahore"], correct_answer:2, explanation:"Three Round Table Conferences were held in London (1930, 1931, 1932) to discuss constitutional reforms for India. Gandhi attended only the second (1931). They eventually led to the Government of India Act, 1935.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Cabinet Mission Plan (1946) proposed:", options:["Partition of India","A three-tier federal structure with united India (no partition)","Dominion status for provinces","Full independence immediately"], correct_answer:1, explanation:"The Cabinet Mission Plan (May 1946) proposed keeping India united under a loose three-tier federation: All-India Union, Groups of provinces, and Individual provinces with maximum autonomy. It tried to prevent partition but ultimately failed.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Who gave the famous 'Tryst with Destiny' speech on 14-15 August 1947?", options:["Mahatma Gandhi","Sardar Patel","Dr. Rajendra Prasad","Jawaharlal Nehru"], correct_answer:3, explanation:"Jawaharlal Nehru gave the iconic 'Tryst with Destiny' speech to the Constituent Assembly at midnight of 14-15 August 1947, marking India's independence. Gandhi was not in Delhi — he was in Calcutta.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The INA (Indian National Army) was led by:", options:["Bhagat Singh","Subhas Chandra Bose","Lala Lajpat Rai","Sardar Patel"], correct_answer:1, explanation:"Subhas Chandra Bose (Netaji) reorganised and led the Indian National Army (Azad Hind Fauj) from 1943. With Japanese help, INA tried to liberate India through military means. His slogan: 'Jai Hind' and 'Give me blood, I will give you freedom'.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },

  // ── HARD (Class 11-12 / UPSC-level) ────────────────────────────────────
  { question_text:"The Hathigumpha inscription (in Odisha) mentions a powerful king named:", options:["Ashoka","Kharavela","Chandragupta II","Samudragupta"], correct_answer:1, explanation:"The Hathigumpha inscription (carved in a cave in Udayagiri, Odisha) records the deeds of Kharavela, king of the Kalinga (Chedi) dynasty, around 1st century BCE. It is an important source for post-Mauryan history.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The Allahabad Pillar inscription records the conquests of:", options:["Ashoka","Chandragupta Maurya","Samudragupta","Chandragupta II"], correct_answer:2, explanation:"The Allahabad Pillar inscription (Prayagraj), composed by Harishena (court poet), records the military campaigns and diplomatic achievements of Samudragupta and is called the 'Poem of Samudragupta'. He is often called the 'Napoleon of India'.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The 'Lucknow Pact' of 1916 was significant because:", options:["It agreed on partition of India","Congress and Muslim League agreed on a joint scheme of constitutional reforms for the first time","It established the Khilafat Movement","It resulted in the Rowlatt Act"], correct_answer:1, explanation:"The Lucknow Pact (December 1916) was an agreement between Congress (Tilak's faction) and the Muslim League (Jinnah) for joint constitutional demands from the British. It marked Hindu-Muslim unity but also accepted separate electorates for Muslims.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The 'Poona Pact' (1932) was signed between Gandhi and:", options:["Jinnah","B.R. Ambedkar","Nehru","Lord Irwin"], correct_answer:1, explanation:"The Poona Pact (September 1932) was signed between Gandhi (who was fasting unto death) and B.R. Ambedkar. It abandoned separate electorates for Depressed Classes (Dalits) in exchange for reserved seats in general electorates — increasing reserved seats from 71 to 147.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The Cripps Mission (1942) failed because:", options:["It offered immediate independence","It offered dominion status after the war but gave no real power immediately — rejected by both Congress and Muslim League","It proposed only partial partition","It was rejected only by the Muslim League"], correct_answer:1, explanation:"Sir Stafford Cripps's 1942 mission offered dominion status after WWII, with option for provinces to opt out. Congress called it a 'post-dated cheque' (Gandhi). The League rejected it too. Its failure led to the Quit India Movement.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The Rowlatt Act (1919) was controversial because:", options:["It taxed Indian goods","It allowed detention without trial for up to 2 years for suspected revolutionaries — no habeas corpus","It partitioned Bengal","It disbanded the Indian Army"], correct_answer:1, explanation:"The Rowlatt Act (Black Act) allowed the government to imprison any person suspected of terrorism for up to 2 years without trial. Gandhi called for a hartal (strike) against it, which led to the Jallianwala Bagh massacre.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The 'Wavell Plan' (1945) proposed:", options:["Immediate independence","A reconstituted Executive Council with equal Hindu-Muslim representation (except for Viceroy and C-in-C)","Partition into two nations","Federal structure with provinces having full autonomy"], correct_answer:1, explanation:"Wavell Plan (Simla Conference, 1945) proposed an interim government with an Executive Council where caste Hindus and Muslims would have equal representation. It failed when Jinnah insisted all Muslim seats go only to Muslim League.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"Which of the following statements about the Indus Valley script is correct?", options:["It has been fully deciphered","It is written left to right","It is an undeciphered script, written boustrophedon (right to left, then left to right)","It is identical to Brahmi script"], correct_answer:2, explanation:"The Indus/Harappan script remains undeciphered. Studies suggest it was written boustrophedon (alternating directions) or right to left. Over 400 signs have been identified. No bilingual inscription like Rosetta Stone has been found.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The Uttaramerur inscription is important because it records:", options:["Chola military victories","A self-governing village system of local elections under the Chola period","The construction of temples","Chola trade with Southeast Asia"], correct_answer:1, explanation:"The Uttaramerur inscription (near Kanchipuram, 10th century CE, Chola period) describes a sophisticated system of village self-governance (sabha) with elected committees (variyams), eligibility criteria, and term limits — an early example of democratic practices.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The book 'Discovery of India' was written by:", options:["Mahatma Gandhi","Sardar Patel","Jawaharlal Nehru","B.R. Ambedkar"], correct_answer:2, explanation:"'Discovery of India' was written by Jawaharlal Nehru while imprisoned at Ahmednagar Fort (1942–1946). It traces Indian history, culture, and philosophy from ancient times to the independence movement.", difficulty:"hard", exam_types:["tnpsc","upsc","ssc"] },
  { question_text:"The Regulating Act of 1773 was significant because:", options:["It transferred power to the Crown","It was the first step by the British Parliament to control the East India Company — created the post of Governor-General","It abolished the company","It gave Indians representation in governance"], correct_answer:1, explanation:"The Regulating Act 1773 was the British Parliament's first attempt to regulate the East India Company. It created the post of Governor-General (Warren Hastings was first), established a Supreme Court at Calcutta, and made company directors report to Parliament.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"Who founded the Ramakrishna Mission (1897) and what was its main purpose?", options:["Ramakrishna Paramahamsa — religious worship only","Swami Vivekananda — combining spiritual practice with social service (education, healthcare for poor)","Annie Besant — Theosophical spirituality","Dayananda Saraswati — Vedic revival"], correct_answer:1, explanation:"Swami Vivekananda founded the Ramakrishna Mission (1897) in Belur Math, Howrah. It combines Vedanta philosophy with humanitarian work — schools, hospitals, disaster relief. Inspired by his guru Sri Ramakrishna Paramahamsa.", difficulty:"hard", exam_types:["tnpsc","upsc","ssc"] },
  { question_text:"The Ryotwari Settlement (introduced in Madras Presidency by Thomas Munro) directly taxed:", options:["Zamindars (landlords)","Individual peasant farmers (ryots) directly — no intermediary","Village communities jointly","Only merchants and traders"], correct_answer:1, explanation:"The Ryotwari system (introduced 1820, Thomas Munro) taxed individual peasants (ryots) directly without intermediary zamindars. Revenue was fixed based on land assessment. Common in Madras and Bombay Presidencies. Mahalwari was used in Northwest India.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
];

async function main() {
  await del();
  console.log('Cleared existing data.');
  const BATCH = 50;
  let total = 0;
  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH);
    await rpush(batch);
    total += batch.length;
    console.log(`Batch ${Math.floor(i/BATCH)+1}: pushed ${batch.length} → total ${total}`);
  }
  console.log(`Done! ${total} history questions in ${KEY}`);
}
main().catch(console.error);
