require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const BASE  = process.env.EXPO_PUBLIC_UPSTASH_REDIS_REST_URL;
const TOKEN = process.env.EXPO_PUBLIC_UPSTASH_REDIS_REST_TOKEN;
const KEY   = 'quiz:subject:biology';
const HDR   = { Authorization:`Bearer ${TOKEN}`, 'Content-Type':'application/json' };
async function rpush(items) {
  const values = items.map(q => JSON.stringify(q));
  const r = await fetch(`${BASE}/pipeline`, {
    method: 'POST', headers: HDR,
    body: JSON.stringify([['RPUSH', KEY, ...values]]),
  });
  return r.json();
}
async function del() {
  return fetch(`${BASE}/del/${encodeURIComponent(KEY)}`, { method: 'POST', headers: HDR }).then(r => r.json());
}

const questions = [
  // ── EASY ──
  { question_text:"The basic structural and functional unit of the kidney is:", options:["Alveolus","Nephron","Villus","Glomerulus"], correct_answer:1, explanation:"The nephron is the functional unit of the kidney. Each kidney has about one million nephrons. It consists of Bowman's capsule, glomerulus, proximal tubule, loop of Henle, distal tubule, and collecting duct.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Chlorophyll is present in:", options:["Nucleus","Mitochondria","Chloroplasts","Vacuoles"], correct_answer:2, explanation:"Chlorophyll is the green photosynthetic pigment located in chloroplasts — specifically in the thylakoid membranes. It absorbs red and blue light but reflects green light (making plants look green).", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The powerhouse of the cell is:", options:["Nucleus","Chloroplast","Ribosome","Mitochondria"], correct_answer:3, explanation:"Mitochondria are called the powerhouse of the cell because they produce ATP (energy currency) through cellular respiration. They have their own DNA and ribosomes — evidence for endosymbiotic theory.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which blood group is the 'universal donor'?", options:["AB+","O+","O−","A−"], correct_answer:2, explanation:"Blood group O− is the universal donor — it has no A, B, or Rh antigens on red blood cells, so it can be given to patients of any blood group in emergencies. AB+ is the universal recipient.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The largest organ of the human body is:", options:["Liver","Brain","Skin","Lungs"], correct_answer:2, explanation:"The skin is the largest organ of the human body, covering about 1.5–2 m². It is the largest organ by surface area and by mass (about 15% of body weight). It protects against infection, regulates temperature, and is sensory.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Insulin is produced by which organ?", options:["Liver","Stomach","Pancreas","Kidney"], correct_answer:2, explanation:"Insulin is produced by the beta cells of the Islets of Langerhans in the pancreas. It regulates blood glucose levels by enabling cells to absorb glucose. Deficiency causes Type 1 diabetes.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Malaria is caused by:", options:["A bacterium","A virus","A protozoan (Plasmodium)","A fungus"], correct_answer:2, explanation:"Malaria is caused by Plasmodium parasites (P. falciparum, P. vivax, P. malariae, P. ovale) and transmitted by the female Anopheles mosquito. P. falciparum causes the most severe (cerebral) malaria.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which vitamin helps in blood clotting?", options:["Vitamin A","Vitamin B12","Vitamin C","Vitamin K"], correct_answer:3, explanation:"Vitamin K (phylloquinone) is essential for the synthesis of clotting factors (II, VII, IX, X). Deficiency leads to excessive bleeding. It is found in leafy green vegetables. Also regulates calcium in bones.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The process of breathing in living organisms is called:", options:["Photosynthesis","Transpiration","Respiration","Excretion"], correct_answer:2, explanation:"Respiration is the process by which organisms break down food (glucose) to release energy. Aerobic respiration: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP. Breathing is the physical act of inhaling/exhaling.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"DNA stands for:", options:["Deoxyribonucleic Acid","Deoxyribose Nucleotide Acid","Di-Nucleic Acid","Diplex Nucleic Acid"], correct_answer:0, explanation:"DNA (Deoxyribonucleic Acid) is the molecule that carries genetic information. It has a double helix structure (discovered by Watson and Crick, 1953). It is found in the nucleus, mitochondria, and chloroplasts.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which part of the brain controls balance and coordination?", options:["Cerebrum","Cerebellum","Medulla oblongata","Hypothalamus"], correct_answer:1, explanation:"Cerebellum ('little brain') controls balance, coordination of movement, and fine motor control. Cerebrum controls thinking, speech, voluntary movement. Medulla oblongata controls involuntary functions (breathing, heart rate).", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Photosynthesis in plants uses which colour of light most effectively?", options:["Green light","Yellow light","Blue and Red light (absorbed by chlorophyll)","UV light"], correct_answer:2, explanation:"Chlorophyll absorbs mainly red light (~660–700 nm) and blue light (~430–450 nm). Green light is mostly reflected (that's why plants are green). These wavelengths drive the light-dependent reactions of photosynthesis.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Bacteria are classified as:", options:["Eukaryotes (have nucleus)","Prokaryotes (no membrane-bound nucleus)","Fungi","Viruses"], correct_answer:1, explanation:"Bacteria are prokaryotes — they lack a membrane-bound nucleus and membrane-bound organelles. Their DNA is in the cytoplasm (nucleoid region). They may have plasmids (small circular DNA). Much simpler than eukaryotic cells.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },

  // ── MEDIUM ──
  { question_text:"Mendel's Law of Segregation states:", options:["Genes for different traits assort independently","During gamete formation, the two alleles for a trait separate (segregate) so each gamete carries only one allele","All traits blend in offspring","Dominant alleles always appear in offspring"], correct_answer:1, explanation:"Mendel's First Law (Law of Segregation): Each organism has two alleles for each trait. During meiosis (gamete formation), alleles segregate so each gamete receives only one allele. In Aa × Aa cross: offspring ratio 1AA:2Aa:1aa (phenotype 3:1).", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Meiosis differs from mitosis in that meiosis:", options:["Produces 2 genetically identical cells","Produces 4 genetically unique haploid cells (gametes) through two divisions","Occurs in all body cells","Does not involve DNA replication"], correct_answer:1, explanation:"Meiosis produces 4 haploid (n) daughter cells that are genetically unique due to crossing over (recombination) and independent assortment. Mitosis produces 2 diploid (2n) genetically identical cells for growth/repair.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Krebs cycle (Citric Acid Cycle) occurs in:", options:["Cytoplasm","Nucleus","Mitochondrial matrix","Endoplasmic reticulum"], correct_answer:2, explanation:"The Krebs cycle occurs in the mitochondrial matrix. It oxidises acetyl-CoA (derived from glucose, fats, proteins) to CO₂, producing NADH, FADH₂, and ATP. These are then used in the electron transport chain (inner mitochondrial membrane).", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The endosymbiotic theory proposes that mitochondria and chloroplasts:", options:["Were formed by cell membrane folding","Evolved from free-living bacteria engulfed by ancestral eukaryotic cells — supported by own DNA, own ribosomes, double membranes","Are always present in all cells","Cannot reproduce independently"], correct_answer:1, explanation:"Lynn Margulis's endosymbiotic theory: Mitochondria evolved from alpha-proteobacteria; chloroplasts from cyanobacteria engulfed by early eukaryotes. Evidence: own circular DNA (like bacteria), 70S ribosomes (like bacteria), double membrane, binary fission reproduction.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Transpiration in plants serves to:", options:["Absorb CO₂","Pull water and minerals up from roots (transpiration pull), cool the plant, and release water vapour","Produce oxygen","Store food"], correct_answer:1, explanation:"Transpiration is the evaporation of water from leaves (mainly through stomata). It creates a tension (transpiration pull) that drives the upward movement of water and dissolved minerals from roots through xylem vessels.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Antibodies are proteins produced by:", options:["Red blood cells","Platelets","B lymphocytes (B cells) — plasma cells","T lymphocytes"], correct_answer:2, explanation:"Antibodies (immunoglobulins) are Y-shaped proteins produced by plasma cells (differentiated B lymphocytes). They recognise and bind to specific antigens (pathogens, toxins), marking them for destruction by the immune system.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The ABO blood group system was discovered by:", options:["Alexander Fleming","Louis Pasteur","Karl Landsteiner","Watson and Crick"], correct_answer:2, explanation:"Karl Landsteiner discovered the ABO blood group system in 1901, for which he won the Nobel Prize in Physiology/Medicine in 1930. He also discovered the Rh factor (with Wiener) in 1937.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"In Darwin's theory of Natural Selection, 'survival of the fittest' means:", options:["The physically strongest organism survives","Organisms best adapted to their environment survive and reproduce more successfully","The largest organism dominates","Fast organisms always survive"], correct_answer:1, explanation:"'Survival of the fittest' (Herbert Spencer's phrase for Darwin's concept): organisms with favourable heritable variations are better adapted to their environment, survive longer, reproduce more, and pass on their traits — gradually changing the population over generations.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Which organelle is responsible for protein synthesis?", options:["Mitochondria","Ribosome","Golgi apparatus","Lysosome"], correct_answer:1, explanation:"Ribosomes are the sites of protein synthesis (translation). They read mRNA and assemble amino acids into proteins. Eukaryotes have 80S ribosomes (60S+40S). Prokaryotes have 70S (50S+30S) — target of many antibiotics.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Plasmids in bacteria are:", options:["Genes on chromosomes","Small, circular, extrachromosomal DNA molecules that can replicate independently — often carry antibiotic resistance genes","Mitochondria-like organelles","Bacterial flagella"], correct_answer:1, explanation:"Plasmids are small, circular, double-stranded DNA molecules separate from the bacterial chromosome. They replicate independently and can transfer between bacteria (conjugation). Often carry antibiotic resistance genes — major concern in medicine.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Human Genome Project (completed 2003) revealed the human genome contains approximately:", options:["3 billion base pairs and ~20,000–25,000 protein-coding genes","3 million base pairs","50,000 genes","100,000 proteins"], correct_answer:0, explanation:"The Human Genome Project (1990–2003) sequenced ~3 billion base pairs of human DNA. Surprisingly only ~20,000–25,000 protein-coding genes (less than expected). Only ~1.5% of DNA codes for proteins — the rest was initially called 'junk DNA' (now known to have regulatory functions).", difficulty:"medium", exam_types:["tnpsc","upsc"] },

  // ── HARD ──
  { question_text:"The lac operon model (Jacob and Monod, 1961) explains:", options:["Transcription of human genes","Gene regulation in E. coli — the lactose operon switches on/off based on lactose availability (inducible operon)","DNA replication mechanisms","Protein folding"], correct_answer:1, explanation:"The lac operon: When lactose is absent, the repressor protein binds the operator and blocks transcription of genes for lactose-metabolising enzymes. When lactose is present, it acts as an inducer — binds the repressor, changes its shape, releases the operator, allowing transcription. First model of gene regulation.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The Meselson-Stahl experiment (1958) proved that DNA replication is:", options:["Conservative (both strands stay together)","Dispersive (strands randomly mix)","Semi-conservative (each new DNA has one original strand + one new strand)","Retrograde"], correct_answer:2, explanation:"Meselson and Stahl labelled E. coli DNA with ¹⁵N (heavy nitrogen), then transferred to ¹⁴N medium. After one replication: all DNA was hybrid (intermediate density). After two replications: half hybrid, half light. This proved semi-conservative replication — each daughter DNA has one original + one new strand.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"PCR (Polymerase Chain Reaction) uses Taq polymerase because:", options:["It is cheapest","It is the most accurate polymerase","It is heat-stable (from Thermus aquaticus, a bacterium in hot springs) — withstands the ~95°C denaturation step","It works at low temperatures"], correct_answer:2, explanation:"PCR amplifies specific DNA segments exponentially. The 95°C denaturation step (separating strands) would destroy normal DNA polymerase. Taq polymerase from Thermus aquaticus (lives in Yellowstone hot springs) is thermostable. Invented by Kary Mullis (Nobel Prize 1993).", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"CRISPR-Cas9 gene editing works by:", options:["Chemically synthesising new genes","Using guide RNA to direct Cas9 (a nuclease/molecular scissors) to cut specific DNA sequences — allowing precise gene editing","Removing entire chromosomes","UV irradiation to mutate DNA"], correct_answer:1, explanation:"CRISPR-Cas9 (from bacterial adaptive immunity): guide RNA (gRNA) is complementary to the target DNA sequence; it directs Cas9 protein to cut the DNA at that exact location. The cell's repair mechanisms either disrupt the gene (NHEJ) or insert new sequence (HDR). Developed by Jennifer Doudna and Emmanuelle Charpentier (Nobel Prize 2020).", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The operon model explains why bacteria are more efficient than eukaryotes in gene regulation because:", options:["Bacteria have more genes","In prokaryotes, multiple functionally related genes are clustered in operons under a single promoter — co-regulated together (coordinately expressed)","Bacteria replicate faster","Bacteria use different genetic code"], correct_answer:1, explanation:"Prokaryotic operons cluster genes with related functions (like lac operon for lactose metabolism) under one promoter — all are switched on or off together. Eukaryotes regulate genes individually (one promoter per gene) and use chromatin remodelling, enhancers, and post-translational modifications.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
];

async function main() {
  await del();
  console.log('Cleared.');
  const BATCH = 50;
  let total = 0;
  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH);
    await rpush(batch);
    total += batch.length;
    console.log(`Batch ${Math.floor(i/BATCH)+1}: pushed ${batch.length} → total ${total}`);
  }
  console.log(`Done! ${total} biology questions in ${KEY}`);
}
main().catch(console.error);
