require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const BASE  = process.env.EXPO_PUBLIC_UPSTASH_REDIS_REST_URL;
const TOKEN = process.env.EXPO_PUBLIC_UPSTASH_REDIS_REST_TOKEN;
const KEY   = 'quiz:subject:science';
const HDR   = { Authorization:`Bearer ${TOKEN}`, 'Content-Type':'application/json' };
async function rpush(items) {
  const values = items.map(q => JSON.stringify(q));
  const r = await fetch(`${BASE}/pipeline`, {
    method: 'POST', headers: HDR,
    body: JSON.stringify([['RPUSH', KEY, ...values]]),
  });
  return r.json();
}
async function del() {
  return fetch(`${BASE}/del/${encodeURIComponent(KEY)}`, { method: 'POST', headers: HDR }).then(r => r.json());
}

const questions = [
  // ── EASY (Class 6-8 NCERT / Samacheer) ──
  { question_text:"Which gas do plants absorb during photosynthesis?", options:["Oxygen","Carbon dioxide","Nitrogen","Hydrogen"], correct_answer:1, explanation:"Plants absorb carbon dioxide (CO₂) from the air during photosynthesis. Using sunlight energy and water, they convert CO₂ into glucose and release oxygen as a by-product.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The process by which plants make their own food using sunlight is called:", options:["Respiration","Transpiration","Photosynthesis","Digestion"], correct_answer:2, explanation:"Photosynthesis: 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ (glucose) + 6O₂. It occurs in the chloroplasts of plant cells using the green pigment chlorophyll.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The organ that pumps blood through the human body is:", options:["Liver","Lung","Kidney","Heart"], correct_answer:3, explanation:"The heart is a muscular organ that pumps blood through the circulatory system. The human heart beats about 72 times per minute (at rest) and pumps about 5 litres of blood per minute.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which part of the plant conducts photosynthesis?", options:["Root","Stem","Leaf","Flower"], correct_answer:2, explanation:"Photosynthesis mainly occurs in leaves, which contain chlorophyll in chloroplasts. Leaves are flat and broad to maximise sunlight absorption.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The smallest unit of life is:", options:["Tissue","Organ","Cell","Molecule"], correct_answer:2, explanation:"The cell is the basic structural and functional unit of all living organisms. Robert Hooke first described cells in 1665 while looking at cork under a microscope.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The force that pulls objects towards the Earth is called:", options:["Friction","Magnetism","Gravity","Tension"], correct_answer:2, explanation:"Gravity (gravitational force) is the attractive force between two masses. Earth's gravity gives weight to physical objects and causes them to fall when dropped. Formulated by Newton as the Law of Universal Gravitation.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which organ in the human body filters blood and produces urine?", options:["Liver","Stomach","Kidney","Lung"], correct_answer:2, explanation:"The kidneys (two bean-shaped organs) filter blood, remove waste products (urea, excess salts), and produce urine. Each kidney contains about 1 million nephrons (functional units).", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The chemical symbol for water is:", options:["H₂O₂","H₂O","HO₂","H₃O"], correct_answer:1, explanation:"Water (H₂O) is composed of 2 hydrogen atoms and 1 oxygen atom. H₂O₂ is hydrogen peroxide. Water is essential for all known life and covers about 71% of Earth's surface.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which planet is closest to the Sun?", options:["Venus","Earth","Mars","Mercury"], correct_answer:3, explanation:"Mercury is the closest planet to the Sun (average distance 57.9 million km). It has no atmosphere to retain heat, so temperatures range from −180°C (night) to 430°C (day).", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Sound cannot travel through:", options:["Air","Water","Steel","Vacuum"], correct_answer:3, explanation:"Sound requires a medium (solid, liquid, or gas) to travel — it cannot travel through a vacuum (empty space). This is why there is no sound in outer space.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"What is the function of red blood cells (RBCs)?", options:["Fight infections","Carry oxygen from lungs to body tissues via haemoglobin","Produce antibodies","Control bleeding"], correct_answer:1, explanation:"Red blood cells (erythrocytes) carry oxygen using haemoglobin (iron-containing protein). They are produced in the bone marrow and live about 120 days. Lack of RBCs causes anaemia.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which gas makes up the majority of Earth's atmosphere?", options:["Oxygen","Carbon dioxide","Nitrogen","Argon"], correct_answer:2, explanation:"Nitrogen makes up about 78% of Earth's atmosphere. Oxygen is about 21%, Argon about 0.93%, CO₂ about 0.04%.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The human body has how many pairs of chromosomes?", options:["23","46","44","22"], correct_answer:0, explanation:"Human body cells have 23 pairs (46 total) chromosomes — 22 pairs of autosomes and 1 pair of sex chromosomes (XX for female, XY for male). Egg and sperm cells (gametes) have 23 single chromosomes.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"An object at rest remains at rest and an object in motion remains in motion unless acted upon by an external force. This is Newton's:", options:["First Law of Motion","Second Law of Motion","Third Law of Motion","Law of Gravitation"], correct_answer:0, explanation:"Newton's First Law (Law of Inertia): A body remains at rest or in uniform motion unless acted upon by a net external force. The tendency to resist change in motion is called 'inertia'.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"What type of mirror is used in vehicles as rear-view mirrors?", options:["Concave mirror","Plane mirror","Convex mirror","Plano-concave mirror"], correct_answer:2, explanation:"Convex mirrors are used as rear-view mirrors because they give a wider field of view (virtual, erect, diminished image). The image is always smaller than the object — 'Objects in mirror are closer than they appear'.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The vitamin that is produced by the skin when exposed to sunlight is:", options:["Vitamin A","Vitamin B12","Vitamin C","Vitamin D"], correct_answer:3, explanation:"Vitamin D is synthesised in the skin when exposed to UVB sunlight. It is essential for calcium absorption and bone health. Deficiency causes rickets (in children) and osteomalacia (in adults).", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },

  // ── MEDIUM (Class 9-10) ──
  { question_text:"The SI unit of electric current is:", options:["Volt","Watt","Ampere","Ohm"], correct_answer:2, explanation:"The SI unit of electric current is the Ampere (A), named after André-Marie Ampère. Current is the flow of electric charge. 1 Ampere = 1 Coulomb per second.", difficulty:"medium", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Ohm's Law states that:", options:["V = IR (voltage equals current times resistance)","P = VI (power equals voltage times current)","F = ma","E = mc²"], correct_answer:0, explanation:"Ohm's Law: V = IR, where V is voltage (volts), I is current (amperes), R is resistance (ohms). This means current is directly proportional to voltage and inversely proportional to resistance.", difficulty:"medium", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The process of conversion of a solid directly into gas (without passing through liquid state) is:", options:["Evaporation","Condensation","Sublimation","Melting"], correct_answer:2, explanation:"Sublimation is the direct conversion of solid to gas (vapour) without passing through liquid phase. Examples: dry ice (solid CO₂), iodine, camphor, naphthalene. The reverse (gas to solid) is deposition.", difficulty:"medium", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The atomic number of an element represents:", options:["Number of neutrons","Number of protons (= number of electrons in neutral atom)","Atomic mass","Number of shells"], correct_answer:1, explanation:"Atomic number (Z) = number of protons in the nucleus = number of electrons in a neutral atom. It uniquely identifies an element. Carbon has Z=6 (6 protons, 6 electrons).", difficulty:"medium", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"In a chemical reaction, if 'reactant A + reactant B → product C + product D', the law of conservation of mass states:", options:["Mass of products > mass of reactants","Mass of reactants = mass of products","Mass is lost in all reactions","Reactants are always more than products"], correct_answer:1, explanation:"Law of Conservation of Mass (Lavoisier, 1789): In a chemical reaction, the total mass of reactants equals the total mass of products. Mass is neither created nor destroyed.", difficulty:"medium", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The pH value of pure water is:", options:["0","7","14","5"], correct_answer:1, explanation:"Pure water has a pH of 7 (neutral). pH < 7 is acidic; pH > 7 is basic/alkaline. pH scale ranges from 0 to 14. Blood is slightly alkaline (pH 7.35–7.45).", difficulty:"medium", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Mitosis results in:", options:["4 haploid daughter cells","2 genetically identical diploid daughter cells","2 haploid daughter cells","4 diploid daughter cells"], correct_answer:1, explanation:"Mitosis (cell division for growth and repair) produces 2 daughter cells that are genetically identical to the parent cell, each with the same number of chromosomes (diploid = 2n). Meiosis produces 4 haploid gametes.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Biodiversity hotspots in India include the Western Ghats and:", options:["Thar Desert","Indo-Burma region and Eastern Himalaya","Deccan Plateau","Sundarbans only"], correct_answer:1, explanation:"India has 4 biodiversity hotspots: Western Ghats & Sri Lanka, Indo-Burma, Eastern Himalaya, and Sundaland (partially). These areas have exceptional species richness and face significant habitat loss (>70% of original habitat lost).", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The 'greenhouse effect' is caused by which gases trapping heat in Earth's atmosphere?", options:["Nitrogen and Oxygen","CO₂, CH₄, N₂O, H₂O vapour, ozone — greenhouse gases","Only CO₂","Only water vapour"], correct_answer:1, explanation:"Greenhouse gases (CO₂, methane CH₄, nitrous oxide N₂O, water vapour, ozone, HFCs) absorb and emit infrared radiation, warming Earth. Without the natural greenhouse effect, Earth would be −18°C. Enhanced greenhouse effect causes global warming.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The speed of light in vacuum is approximately:", options:["3 × 10⁶ m/s","3 × 10⁸ m/s","3 × 10¹⁰ m/s","3 × 10⁴ m/s"], correct_answer:1, explanation:"Speed of light in vacuum (c) = 3 × 10⁸ m/s (approximately 300,000 km/s). Light takes about 8 minutes 20 seconds to travel from the Sun to Earth. It is the maximum speed in the universe.", difficulty:"medium", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Which of the following is an example of a chemical change?", options:["Melting of ice","Dissolving sugar in water","Rusting of iron","Cutting paper"], correct_answer:2, explanation:"Rusting of iron (Fe + O₂ + H₂O → Fe₂O₃·H₂O) is a chemical change — new substance formed, process irreversible. Melting, dissolving, cutting are physical changes — no new substance is formed.", difficulty:"medium", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The functional unit of the kidney is:", options:["Alveolus","Nephron","Villus","Islet of Langerhans"], correct_answer:1, explanation:"The nephron is the structural and functional unit of the kidney. Each kidney has about 1 million nephrons. It filters blood, reabsorbs useful substances, and forms urine.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Valence electrons are electrons in:", options:["The nucleus","The innermost shell","The outermost (valence) shell — these determine chemical properties and bonding","All shells equally"], correct_answer:2, explanation:"Valence electrons are in the outermost electron shell. They determine the chemical behaviour of an element. Elements with similar valence electrons have similar properties (same group in periodic table).", difficulty:"medium", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The process by which a liquid changes to a gas at its surface at any temperature is called:", options:["Boiling","Condensation","Evaporation","Sublimation"], correct_answer:2, explanation:"Evaporation occurs at any temperature from the surface of a liquid (not throughout the liquid). Boiling occurs throughout the liquid at a specific temperature (boiling point). Evaporation is a cooling process.", difficulty:"medium", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The 'ozone layer' in the atmosphere is mainly found in:", options:["Troposphere (0–12 km)","Stratosphere (15–35 km)","Mesosphere (50–85 km)","Thermosphere"], correct_answer:1, explanation:"The ozone layer is in the stratosphere at 15–35 km altitude. It absorbs 93–99% of the Sun's harmful UV-B and UV-C radiation. CFCs (chlorofluorocarbons) deplete ozone — Montreal Protocol (1987) controls them.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },

  // ── HARD (Class 11-12 / Competitive) ──
  { question_text:"The work-energy theorem states that the net work done on an object equals:", options:["The change in potential energy","The change in kinetic energy of the object","The total force applied","The displacement times friction"], correct_answer:1, explanation:"Work-Energy Theorem: W_net = ΔKE = ½mv² − ½mu². The net work done on an object equals the change in its kinetic energy. This connects kinematics and dynamics.", difficulty:"hard", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"During nuclear fission:", options:["Two light nuclei fuse to form a heavier nucleus","A heavy nucleus splits into two smaller nuclei releasing enormous energy","Neutrons are absorbed without energy release","Electrons are emitted from the nucleus"], correct_answer:1, explanation:"Nuclear fission: a heavy nucleus (like U-235 or Pu-239) splits into two smaller nuclei (daughter nuclei) + 2-3 neutrons + enormous energy (from mass-energy equivalence E=mc²). Used in nuclear reactors and atomic bombs.", difficulty:"hard", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The photoelectric effect (for which Einstein won the Nobel Prize) demonstrated that:", options:["Light behaves only as a wave","Light consists of particles (photons) — energy E = hf (frequency dependent, not intensity)","Electrons can travel faster than light","Metals emit radiation when heated"], correct_answer:1, explanation:"The Photoelectric Effect: Einstein (1905) explained that light consists of photons (energy E = hf). Metal emits electrons only if photon frequency exceeds the threshold frequency — regardless of intensity. This established the quantum nature of light (wave-particle duality).", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"Enzyme inhibitors in biochemistry work by:", options:["Increasing substrate concentration","Competitively (binding to active site) or non-competitively (binding to allosteric site) blocking enzyme activity","Changing the temperature","Removing cofactors"], correct_answer:1, explanation:"Enzyme inhibitors: Competitive inhibitors bind the active site (compete with substrate). Non-competitive inhibitors bind allosteric sites and change enzyme shape. Both reduce enzyme activity. Many drugs are enzyme inhibitors (e.g., statins inhibit HMG-CoA reductase).", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The Hardy-Weinberg equilibrium states that allele frequencies in a population remain constant if:", options:["There is natural selection","There is no mutation, no migration, random mating, large population, no natural selection","There is genetic drift","The population is small"], correct_answer:1, explanation:"Hardy-Weinberg Equilibrium (p² + 2pq + q² = 1) states allele and genotype frequencies remain stable over generations if: random mating, no mutation, no migration (gene flow), no natural selection, infinitely large population. Deviations indicate evolution is occurring.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The Heisenberg Uncertainty Principle states:", options:["Energy is conserved in all reactions","It is impossible to simultaneously know both the exact position and exact momentum of a particle","The speed of light is constant","Electrons orbit the nucleus in fixed paths"], correct_answer:1, explanation:"Heisenberg's Uncertainty Principle (1927): Δx · Δp ≥ ℏ/2. You cannot precisely measure both the position (Δx) and momentum (Δp) of a particle simultaneously. The more precisely you know one, the less precisely you can know the other — a fundamental quantum mechanical principle.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"Recombinant DNA technology (genetic engineering) involves:", options:["Natural selection of organisms","Cutting DNA at specific sequences using restriction enzymes and inserting it into a host organism's DNA","UV radiation to mutate DNA","Mixing cells without altering DNA"], correct_answer:1, explanation:"Recombinant DNA technology: restriction enzymes (molecular scissors) cut DNA at specific palindromic sequences; the target gene is ligated into a vector (plasmid/virus); the vector is introduced into a host cell (bacteria, yeast) which then produces the desired protein. Used for insulin, growth hormone, vaccines.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
];

async function main() {
  await del();
  console.log('Cleared existing data.');
  const BATCH = 50;
  let total = 0;
  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH);
    await rpush(batch);
    total += batch.length;
    console.log(`Batch ${Math.floor(i/BATCH)+1}: pushed ${batch.length} → total ${total}`);
  }
  console.log(`Done! ${total} science questions in ${KEY}`);
}
main().catch(console.error);
