require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const BASE  = process.env.EXPO_PUBLIC_UPSTASH_REDIS_REST_URL;
const TOKEN = process.env.EXPO_PUBLIC_UPSTASH_REDIS_REST_TOKEN;
const KEY   = 'quiz:subject:polity';
const HDR   = { Authorization:`Bearer ${TOKEN}`, 'Content-Type':'application/json' };

async function rpush(items) {
  const values = items.map(q => JSON.stringify(q));
  const r = await fetch(`${BASE}/pipeline`, {
    method: 'POST', headers: HDR,
    body: JSON.stringify([['RPUSH', KEY, ...values]]),
  });
  return r.json();
}
async function del() {
  return fetch(`${BASE}/del/${encodeURIComponent(KEY)}`, { method: 'POST', headers: HDR }).then(r => r.json());
}

const questions = [
  // ── EASY ──
  { question_text:"The Constitution of India came into force on:", options:["15 August 1947","26 November 1949","26 January 1950","2 October 1950"], correct_answer:2, explanation:"The Indian Constitution was adopted on 26 November 1949 but came into effect on 26 January 1950, chosen to commemorate the Purna Swaraj declaration of 1930. 26 January is celebrated as Republic Day.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb","banking"] },
  { question_text:"Who is called the 'Father of the Indian Constitution'?", options:["Mahatma Gandhi","Jawaharlal Nehru","B.R. Ambedkar","Sardar Patel"], correct_answer:2, explanation:"Dr. B.R. Ambedkar chaired the Drafting Committee of the Constitution and played the key role in drafting it. He is called the Father of the Indian Constitution.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb","banking"] },
  { question_text:"India is described as a 'Union of States' in:", options:["Article 1","Article 5","Article 19","Article 32"], correct_answer:0, explanation:"Article 1 of the Indian Constitution describes India (Bharat) as 'a Union of States'. The word 'Union' (not Federation) was used to emphasize that states cannot secede from the Union.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb","banking"] },
  { question_text:"The Preamble of the Indian Constitution begins with:", options:["'We the Parliament of India'","'We the People of India'","'I, the President of India'","'By order of the Governor-General'"], correct_answer:1, explanation:"The Preamble begins with 'WE, THE PEOPLE OF INDIA', indicating that the ultimate authority rests with the people. It was inspired by the US Constitution's Preamble.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb","banking"] },
  { question_text:"What does 'Sovereign' in the Preamble mean?", options:["India is ruled by a king","India is subject to another country","India is independent — not under the authority of any external power","India has a single religion"], correct_answer:2, explanation:"'Sovereign' means India is independent and not subject to any external authority. India makes its own laws (both internal and external affairs) without interference from any other country.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"What does 'Secular' in the Indian Constitution mean?", options:["India has no religion","India has an official state religion (Hinduism)","The state has no official religion — equal treatment of all religions","Only Hindu practices are allowed in government"], correct_answer:2, explanation:"'Secular' (added by the 42nd Amendment, 1976) means the Indian state has no official religion, treats all religions equally, and does not discriminate based on religion. Citizens are free to practice any religion.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Fundamental Rights of Indian citizens are found in which Part of the Constitution?", options:["Part II","Part III","Part IV","Part V"], correct_answer:1, explanation:"Fundamental Rights are in Part III of the Indian Constitution (Articles 12–35). They are justiciable — citizens can approach the Supreme Court/High Courts to enforce them.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb","banking"] },
  { question_text:"The Right to Constitutional Remedies is guaranteed by:", options:["Article 14","Article 21","Article 32","Article 19"], correct_answer:2, explanation:"Article 32 gives citizens the right to approach the Supreme Court for enforcement of Fundamental Rights. Dr. Ambedkar called Article 32 'the heart and soul of the Constitution'.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb","banking"] },
  { question_text:"The Directive Principles of State Policy are found in which Part?", options:["Part II","Part III","Part IV","Part V"], correct_answer:2, explanation:"Directive Principles of State Policy (DPSP) are in Part IV (Articles 36–51). They are non-justiciable (cannot be enforced in court) but are fundamental in governance — directive for state policy.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"Who is the head of state of India?", options:["Prime Minister","Chief Justice","President","Speaker of Lok Sabha"], correct_answer:2, explanation:"The President of India is the Constitutional Head of State. The President is the ceremonial head. Real executive power is exercised by the Prime Minister and the Council of Ministers.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb","banking"] },
  { question_text:"The minimum age to become the President of India is:", options:["25 years","30 years","35 years","40 years"], correct_answer:2, explanation:"To be eligible as President: Indian citizen, 35+ years old, qualified to be a Lok Sabha member, not hold any office of profit. The President is elected indirectly by an Electoral College.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The Prime Minister of India is appointed by:", options:["Lok Sabha members by vote","The President of India","The Supreme Court","The Vice President"], correct_answer:1, explanation:"The President appoints the leader of the majority party/coalition in Lok Sabha as Prime Minister. The Prime Minister then advises the President on appointing other ministers.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb","banking"] },
  { question_text:"Lok Sabha has a maximum strength of:", options:["543","545","552","550"], correct_answer:2, explanation:"Lok Sabha (House of the People) has a maximum strength of 552: up to 530 members from states, up to 20 from UTs, and 2 nominated Anglo-Indians (now abolished by 104th Amendment 2020). Currently 543 elected seats.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"The minimum age to vote in Indian elections is:", options:["21 years","18 years","25 years","16 years"], correct_answer:1, explanation:"The voting age in India was lowered from 21 to 18 years by the 61st Constitutional Amendment Act, 1988 (effective from 1989). This gave crores of youth the right to vote.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb","banking"] },
  { question_text:"Which court is the guardian of the Indian Constitution?", options:["High Court","District Court","Supreme Court","Consumer Court"], correct_answer:2, explanation:"The Supreme Court of India is the guardian and final interpreter of the Constitution. It has original, appellate, and advisory jurisdiction. Located in New Delhi.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb","banking"] },
  { question_text:"The concept of 'Judicial Review' in India means:", options:["Parliament can review court decisions","Courts can examine laws and declare them unconstitutional if they violate the Constitution","Judges review their own judgments","Citizens can review court fees"], correct_answer:1, explanation:"Judicial Review is the power of courts (especially the Supreme Court) to examine the constitutional validity of legislative and executive actions and strike them down if they violate the Constitution.", difficulty:"easy", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Election Commission of India is a:", options:["Ministry under the Home Ministry","Constitutional body under Article 324","Statutory body under Parliament Act","Advisory body under the President"], correct_answer:1, explanation:"The Election Commission of India (ECI) is a permanent independent constitutional body under Article 324. It superintends, directs, and controls elections to Parliament, State Legislatures, President, and Vice President.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },
  { question_text:"India's Parliament consists of:", options:["Lok Sabha only","Lok Sabha and Rajya Sabha","Lok Sabha, Rajya Sabha and President","Supreme Court and Parliament"], correct_answer:2, explanation:"India's Parliament has three parts: President + Lok Sabha (Lower House/House of the People) + Rajya Sabha (Upper House/Council of States). Together they constitute Parliament under Article 79.", difficulty:"easy", exam_types:["tnpsc","ssc","rrb"] },

  // ── MEDIUM ──
  { question_text:"The writ of 'Habeas Corpus' literally means:", options:["To prohibit","You may have the body — used to release unlawfully detained persons","To be certified","To do the act"], correct_answer:1, explanation:"Habeas Corpus ('you may have the body') is a writ issued to a person who has unlawfully detained another. The court orders the detaining authority to produce the person and justify detention. It protects personal liberty.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc","banking"] },
  { question_text:"The writ of 'Mandamus' means:", options:["We command — courts order a public official/body to perform a duty they have failed to perform","We certify","To bring up","To prohibit"], correct_answer:0, explanation:"Mandamus ('We command') is a court order directing a government official, lower court, or public body to perform a mandatory public duty. It cannot be issued against private individuals.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Article 21 of the Constitution guarantees:", options:["Right to Equality","Right to Life and Personal Liberty — no person shall be deprived except by procedure established by law","Right to Freedom of Speech","Right against Exploitation"], correct_answer:1, explanation:"Article 21: 'No person shall be deprived of his life or personal liberty except according to procedure established by law.' The Supreme Court has expanded this to include right to livelihood, education, health, environment, privacy, and more.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc","banking"] },
  { question_text:"Article 14 guarantees:", options:["Freedom of speech","Right to equality before law and equal protection of law","Right against exploitation","Freedom of religion"], correct_answer:1, explanation:"Article 14: 'The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.' It is the most fundamental provision — every person is equal before law.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The 'Golden Triangle' of fundamental rights refers to Articles:", options:["14, 19 and 21","12, 13 and 32","19, 20 and 22","15, 16 and 17"], correct_answer:0, explanation:"Articles 14 (Equality), 19 (Six Freedoms), and 21 (Life and Liberty) are called the 'Golden Triangle' — any law that violates any one of these three articles is void. Established in Maneka Gandhi vs Union of India (1978).", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Which article abolishes untouchability?", options:["Article 14","Article 15","Article 17","Article 19"], correct_answer:2, explanation:"Article 17 abolishes untouchability and its practice in any form is forbidden. The Protection of Civil Rights Act 1955 and SC/ST (Prevention of Atrocities) Act 1989 enforce this provision.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc","rrb"] },
  { question_text:"The 42nd Constitutional Amendment (1976) is called the 'Mini-Constitution' because:", options:["It was a small amendment","It made sweeping changes: added 'Socialist' and 'Secular' to Preamble, added Fundamental Duties, curtailed judicial review","It amended only 42 articles","It was passed in 42 days"], correct_answer:1, explanation:"The 42nd Amendment (during Emergency, 1976) was the most significant: added 'Socialist', 'Secular', 'Integrity' to Preamble; added Fundamental Duties (Part IVA, Article 51A); added 3 subjects to Concurrent List; curtailed Supreme Court powers.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Fundamental Duties were added to the Constitution by the ___ Amendment:", options:["40th","42nd","44th","86th"], correct_answer:1, explanation:"Fundamental Duties (Article 51A) were added by the 42nd Amendment Act 1976, on the recommendation of the Swaran Singh Committee. Originally 10 duties; the 86th Amendment (2002) added an 11th duty (provide education to children).", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The 'Basic Structure Doctrine' of the Indian Constitution was established in:", options:["Golaknath vs State of Punjab (1967)","Kesavananda Bharati vs State of Kerala (1973)","Minerva Mills vs Union of India (1980)","Maneka Gandhi vs Union of India (1978)"], correct_answer:1, explanation:"In Kesavananda Bharati vs State of Kerala (1973), the Supreme Court (13-judge bench) ruled that Parliament can amend the Constitution under Article 368, but cannot destroy its 'basic structure' (democracy, federalism, secularism, judicial review, etc.).", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Rajya Sabha is a permanent house because:", options:["It has lifetime members","It is never dissolved — one-third of its members retire every two years","The President is its presiding officer","Members are elected for 10 years"], correct_answer:1, explanation:"Unlike Lok Sabha (which can be dissolved), Rajya Sabha is a permanent body. It has 250 members (238 elected + 12 nominated). Members serve 6-year terms, with 1/3 retiring every 2 years.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc","rrb"] },
  { question_text:"Which article deals with the right of minorities to establish educational institutions?", options:["Article 25","Article 28","Article 29","Article 30"], correct_answer:3, explanation:"Article 30 gives minorities (religious or linguistic) the right to establish and administer educational institutions of their choice. The state cannot discriminate in granting aid to such institutions.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The Comptroller and Auditor General (CAG) of India audits:", options:["Only central government accounts","Accounts of Union Government, State Governments, and all government-owned companies","Only the RBI accounts","Only defence expenditure"], correct_answer:1, explanation:"The CAG (Constitutional post under Article 148) audits accounts of the Union Government, all State Governments, government-owned corporations, and bodies receiving government grants. CAG reports are laid before Parliament/State Legislatures.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Article 356 (President's Rule) is imposed when:", options:["The President wishes to govern directly","The constitutional machinery in a state fails — state cannot be governed in accordance with the Constitution","A state requests direct Union rule","The PM advises it without Cabinet consensus"], correct_answer:1, explanation:"Article 356 allows the President (on Governor's report) to assume governance of a state when constitutional machinery breaks down. It effectively means dissolution of state legislative assembly and direct central rule. The Supreme Court in S.R. Bommai case (1994) limited its misuse.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Zero Hour in Parliament refers to:", options:["The first hour of Parliament session","The time immediately after Question Hour (12 noon) when members raise urgent matters of public importance without prior notice","The time Parliament closes","The time for Presidential address"], correct_answer:1, explanation:"Zero Hour (starting around 12 noon) is when MPs can raise important public issues without prior notice or permission. It is not mentioned in the rules of procedure — it is an Indian parliamentary innovation since the 1960s.", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The concept of 'Money Bill' is defined in:", options:["Article 108","Article 109","Article 110","Article 112"], correct_answer:2, explanation:"Article 110 defines a Money Bill: it deals only with taxation, borrowing by government, custody of Consolidated Fund, etc. A Money Bill can only be introduced in Lok Sabha — Rajya Sabha can only make recommendations (not reject).", difficulty:"medium", exam_types:["tnpsc","ssc","upsc"] },

  // ── HARD ──
  { question_text:"In S.R. Bommai vs Union of India (1994), the Supreme Court ruled:", options:["Article 356 cannot be challenged in courts","Imposition of President's Rule is subject to judicial review; floor test must be held before dismissing the government","States can secede from the Union","Governor has absolute discretion to recommend President's Rule"], correct_answer:1, explanation:"The landmark S.R. Bommai judgment (9-judge bench) ruled: (1) President's Rule imposition is judicially reviewable; (2) the government must be given a floor test before dismissal; (3) Secularism is part of the Basic Structure. This curbed misuse of Article 356.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The 'Doctrine of Eclipse' in Indian Constitutional law refers to:", options:["Laws become permanently void if they violate Fundamental Rights","Pre-Constitutional laws inconsistent with Fundamental Rights are eclipsed (dormant) but can be revived if the Fundamental Right is amended","Laws are struck down permanently","Court decisions that override Parliament"], correct_answer:1, explanation:"Doctrine of Eclipse (Bhikaji Narain Dhakras case, 1955): Pre-constitutional laws inconsistent with Fundamental Rights become dormant (not void), and if the relevant Fundamental Right is amended to remove inconsistency, such laws revive automatically.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"Which constitutional provision has been described by the Supreme Court as the 'due process of law' equivalent?", options:["Article 13","Article 21 as interpreted in Maneka Gandhi case (1978)","Article 32","Article 14"], correct_answer:1, explanation:"In Maneka Gandhi vs Union of India (1978), the Supreme Court interpreted Article 21's 'procedure established by law' to include 'due process' — the procedure must be fair, just, and reasonable, not merely any procedure. This was a historic expansion of Article 21.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The 'Doctrine of Severability' means:", options:["A law can be split into valid and invalid parts — only the invalid part is struck down","The entire law is struck down if any part violates Constitution","Parliament and State Legislatures can sever ties","Federal units can separate from the Union"], correct_answer:0, explanation:"Doctrine of Severability/Separability: If a law contains some provisions that violate the Constitution and some that don't, only the unconstitutional part is struck down — the rest of the law remains valid (if severable). Applied in R.M.D.C. vs Union of India (1957).", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"Which amendment gave constitutional status to Panchayati Raj institutions?", options:["42nd Amendment","73rd Amendment 1992","86th Amendment","91st Amendment"], correct_answer:1, explanation:"The 73rd Constitutional Amendment Act 1992 gave constitutional status to Panchayati Raj (added Part IX, Articles 243–243O, and 11th Schedule with 29 subjects). It made elections mandatory, reserved seats for SC/ST/women. Came into force: April 1993.", difficulty:"hard", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Article 19(1) guarantees six freedoms. Which of these was originally one but is NO LONGER a fundamental right?", options:["Freedom of speech","Right to property","Freedom of movement","Freedom of profession"], correct_answer:1, explanation:"The Right to Property (Article 19(1)(f) and Article 31) was originally a Fundamental Right. The 44th Amendment Act 1978 removed it from Fundamental Rights and made it a constitutional/legal right under Article 300A ('No person shall be deprived of his property save by authority of law').", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"The 'Anti-Defection Law' is in:", options:["Article 102","Article 191","10th Schedule (added by 52nd Amendment 1985)","8th Schedule"], correct_answer:2, explanation:"The Anti-Defection Law is in the 10th Schedule (added by the 52nd Amendment Act 1985). It disqualifies a legislator who voluntarily gives up membership of the party, votes against the party whip, or abstains from voting without permission.", difficulty:"hard", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"Under the 'First-Past-the-Post' (FPTP) system used in India for Lok Sabha elections:", options:["A candidate needs 50%+1 votes to win","The candidate with the most votes in a constituency wins, even without absolute majority","Votes are proportionally distributed to parties","Parties nominate candidates without public voting"], correct_answer:1, explanation:"India uses FPTP (simple majority/plurality) for Lok Sabha and State Assembly elections: the candidate who gets more votes than any other candidate in the constituency wins, regardless of whether it is an absolute majority. This can lead to a party winning with under 30% of votes.", difficulty:"hard", exam_types:["tnpsc","ssc","upsc"] },
  { question_text:"The CAG of India is appointed by:", options:["Prime Minister","Parliament","President of India — and can be removed only by impeachment like a Supreme Court judge","Finance Minister"], correct_answer:2, explanation:"The CAG (Article 148) is appointed by the President and can be removed only by an address of Parliament (same process as removal of a Supreme Court judge). The CAG is independent of the executive to ensure impartial audit.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
  { question_text:"Which schedule of the Indian Constitution contains the 'Oath of Secrecy' taken by ministers?", options:["First Schedule","Second Schedule","Third Schedule","Fourth Schedule"], correct_answer:2, explanation:"The Third Schedule contains forms of Oaths and Affirmations: oath taken by Union Ministers, MPs, President, Vice President, judges of Supreme Court and High Courts, CAG, and State Ministers and MLAs.", difficulty:"hard", exam_types:["tnpsc","upsc"] },
];

async function main() {
  await del();
  console.log('Cleared existing data.');
  const BATCH = 50;
  let total = 0;
  for (let i = 0; i < questions.length; i += BATCH) {
    const batch = questions.slice(i, i + BATCH);
    await rpush(batch);
    total += batch.length;
    console.log(`Batch ${Math.floor(i/BATCH)+1}: pushed ${batch.length} → total ${total}`);
  }
  console.log(`Done! ${total} polity questions in ${KEY}`);
}
main().catch(console.error);
