import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

type MissionPlanBlock = {
  block?: number;
  topic: string;
  duration_minutes: number;
  objective?: string;
  method?: string;
};

type MissionPlan = {
  title?: string;
  schedule?: MissionPlanBlock[];
  focus?: {
    block_apps?: string[];
    duration_minutes?: number;
  };
  whatsapp_plan?: Array<{ at_minute: number; type: string; topic?: string }>;
  monetization?: Record<string, unknown>;
};

type MissionModeratorRequest = {
  user_id: string;
  topic: string;
  duration_minutes?: number;
  plan?: MissionPlan;
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const body = (await req.json()) as MissionModeratorRequest;
    if (!body.user_id || !body.topic) {
      return new Response(JSON.stringify({ error: "Missing parameters" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    );

    const plan = body.plan;
    const schedule = plan?.schedule ?? [];

    const durationFromPlan =
      schedule.length > 0
        ? schedule.reduce((acc, block) => acc + (block.duration_minutes ?? 0), 0)
        : null;

    const duration = durationFromPlan ?? Math.max(20, body.duration_minutes ?? 60);
    const blockOne = Math.round(duration * 0.5);
    const blockTwo = Math.round(duration * 0.35);
    const blockThree = Math.max(5, duration - blockOne - blockTwo);

    const metadata = {
      plan,
      focus_blocked_apps: plan?.focus?.block_apps ?? ["Instagram", "YouTube", "WhatsApp"],
      whatsapp_plan:
        plan?.whatsapp_plan ??
        [
          { at_minute: 0, type: "plan_ready" },
          { at_minute: blockOne, type: "mid_session" },
          { at_minute: duration, type: "mission_complete" },
        ],
      duration_minutes: duration,
    };

    const { data: mission, error: missionError } = await supabase
      .from("missions")
      .insert({
        user_id: body.user_id,
        title: plan?.title ?? body.topic,
        description: plan?.title ? `Mission: ${plan.title}` : `Autogenerated mission for ${body.topic}`,
        content_type: "mission_plan",
        content_summary: `Focus protocol for ${body.topic}`,
        content_text: JSON.stringify(schedule),
        subject_name: plan?.title ?? body.topic,
        estimated_time: duration,
        xp_reward: 0,
        status: "planning",
        total_rooms: schedule.length > 0 ? schedule.length : 3,
        completed_rooms: 0,
        content_analysis: metadata,
      })
      .select("*")
      .single();

    if (missionError) throw missionError;

    const defaultBlocks = [
      {
        sequence: 1,
        title: "Core Concepts",
        objective: "Understand the fundamentals",
        duration_minutes: blockOne,
        method: "Active reading + recall prompts",
      },
      {
        sequence: 2,
        title: "Exam Traps",
        objective: "Tackle tricky MCQs and PYQs",
        duration_minutes: blockTwo,
        method: "Timed drills",
      },
      {
        sequence: 3,
        title: "Rapid Recall",
        objective: "Summarize and reinforce memory",
        duration_minutes: blockThree,
        method: "Feynman technique + flash recap",
      },
    ];

    const blocksPayload =
      schedule.length > 0
        ? schedule.map((block, index) => ({
            mission_id: mission.id,
            sequence: block.block ?? index + 1,
            title: block.topic,
            objective: block.objective ?? "",
            duration_minutes: block.duration_minutes,
            method: block.method ?? "",
          }))
        : defaultBlocks;

    return new Response(
      JSON.stringify({
        mission: {
          ...mission,
          metadata: plan ?? mission.content_analysis ?? {},
        },
        blocks: blocksPayload,
        plan,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      },
    );
  } catch (error) {
    console.error("mission_moderator error", error);
    return new Response(JSON.stringify({ error: error.message ?? "Server error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
